const id = "Tasktracker.mdx";
						const collection = "projects";
						const slug = "tasktracker";
						const body = "\nimport TextSplit from \"../../components/casestudy/TextSplit.astro\";\n\n### Introduction\n\nTasktracker is my take on a task tracking application. I know there are a lot out there, made by a team of professionales,\nbut sometimes you just want to make something yourself. It may be better or worse, but it's yours.\nThe idea came from the podcast `Syntax` by Wes Bos and Scott Tolinski. They talked about a task list and daily task application that one of them had made.\nIt was quite intriguing to me, so I checked it out, and in my humble, honest opinion, I could do better.\nSo that is what this is. My take on a task tracking application.\n\n#### My goals with Tasktracker\n\nI am really bad at following a task tracker / todo list. So i needed something that would motivate me to use it.\nI have looked at multiple motivational components in different apps like, Duolingo, where they use the streak and daily rewards to motivate the user.\nAlso, if someone is actually going to use an application like this, it need to be simple.\nNo one is going to go through a 10 button process to clear one goal, or get a reward or for simply adding a task.\nIt really need to be simple, intuative and `fun`.\n\n##### Step 1: Planning, Sketches and Wireframes\n\n<TextSplit ltr={true}>\n  I really needed to find an intuative way to layout the application. Do I want\n  the user to see all the tasks at once, or do I want the user to see one task\n  at a time? Do i want the dailies to be the first thing they see? or should\n  they click on daily tasks to see them? Should the Add Task button also be on\n  the front page?\n</TextSplit>\n\n<TextSplit ltr={false}>\n  I really needed to find an intuative way to layout the application. Do I want\n  the user to see all the tasks at once, or do I want the user to see one task\n  at a time? Do i want the dailies to be the first thing they see? or should\n  they click on daily tasks to see them? Should the Add Task button also be on\n  the front page?\n</TextSplit>\n";
						const data = {title:"Tasktracker",description:"Track your task with intuative design, motivation and a sense of accomplishment.",image:"/holidazefrontpage.png",imageMobile:"/Holidazemobile.png",githubRepo:"https://github.com/MathiasGuGu/Holidaze",liveDemo:"https://bookatholidaze.netlify.app"};
						const _internal = {
							type: 'content',
							filePath: "/Users/magugu/Documents/Developer/Noroff - Tasks, Courses, CAs/Course Assignment/portfolio/src/content/projects/Tasktracker.mdx",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
